[[redirects]]
  from = "/go"
  to = "/?utm_source=school&utm_medium=printedskfbrochure&utm_campaign=studentbrochure"

[[redirects]]
  from = "/accepted"
  to = "/"

[[redirects]]
  from = "/data-science-accepted"
  to = "/"

[[redirects]]
  from = "/web-development-accepted"
  to = "/"
